### PR TITLE
feat: update default zitadel version to v2.46.0 with init projections

### PR DESCRIPTION
**Pull request by eliobischof**
- Updates the default ZITADEL version
- Closes https://github.com/zitadel/zitadel-charts/issues/168.
- Updates test dependencies

This Commit adds the ability to specify additional arguments to pass to the setup job besides the preconfigured ones. By default, --init-projections=true is passed. This ensures that the setup job properly migrates the database between versions.

### Definition of Ready

- [ ] I am happy with the code
- [ ] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [ ] My code has no repetitions
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] If possible, [the test configuration](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/test/installation/config_test.go) is adjusted so acceptance tests cover my changes

### CODE REVIEW

**Comment by meyfa** [comment]
Re @eliobischof in #170:

> we need to merge #160 first

Since #170 depends on `--init-projections` which was added in Zitadel v2.43.6, should this maybe be changed to set the app version to v2.43.6? Or even better, directly to v2.44.1.

**Comment by meyfa** [comment]
Nit: I think the PR title could be updated to reflect the updated version :)

**Comment by meyfa** [comment]
Is there an expected timeline for merging this PR? There have been further Zitadel releases, and I would feel much safer updating if #170 was released, but it depends on this PR.

**Comment by eliobischof** [comment]
> Is there an expected timeline for merging this PR? There have been further Zitadel releases, and I would feel much safer updating if #170 was released, but it depends on this PR.

I merged #170 because I think these changes should be released together.

**Comment by eliobischof** [comment]
@stebenz can you review this, plz?

**Comment by eliobischof** [comment]
@stebenz can you review, plz?

**Review by stebenz — APPROVED** [review]

**Pull request merged**
