### PR TITLE
feat: use k8s init and setup jobs and remove cockroach chart dependency

### PR DESCRIPTION
**Pull request by eliobischof**
What changes:
Helm pre-update hooks for running `zitadel setup` and `zitadel-init` are used for dedicated jobs with dedicated activeTimeoutSeconds.

Implications:
- The startupProbe section is configured more aggressively as they now start only after the setup job is complete. This enables faster rollouts.
- Less friction during upgrade setup phase, as `zitadel setup` is executed by a single pod.
- The default initialDelaySeconds are set to 0 because startupProbes are configured by default, making them obsolete.
- Support vor k8s v1.16 and v1.17 is removed, as startupProbe was introduced in k8s v1.18
- For keeping the changes compatible with tools that execute `helm template | kubectl apply` like ArgoCD, the CockroachDB chart dependency is removed and a new major version is released. The upgrade path is described in the README.md

Also in this PR:
- The default ZITADEL version is bumped to v2.15.0

### CODE REVIEW

**Comment by eliobischof** [comment]
@DoGab do you have any objections regarding the new default timeouts?

**Comment by DoGab** [comment]
> @DoGab do you have any objections regarding the new default timeouts?

No that seems legit to me! We can set them to 0

**Comment by DoGab** [comment]
I quickly looked through the PR and found 2 things.

**Helm hooks**
Do you know how the helm hooks work together with ArgoCD hooks? I guess that we need to map helm hooks to ArgoCD hooks by changing the annotations. I would suggest the helm hook annotations should be able to be excluded or overridden by custom annotations from the values file.

**Jobs with Istio**
When using istio it is required to inject a waiting command at the beginning of the jobs execution. It requires to call an istio endpoint otherwise the job will never complete because istio doesn't know when the job has finished. [This example](https://github.com/istio/istio/issues/11659#issuecomment-479547294) shows how to achieve this. If we could have a value that allows to inject such a code snippet at the start of the job, this would be great.

**Comment by eliobischof** [comment]
@DoGab i added the extraContainers property to the setupJob config https://github.com/zitadel/zitadel-charts/pull/48/commits/5ae912aef02152d905856a00c48168312e61f09f.
Please let me know if it helps with making it compatible with Istio.

**Comment by DoGab** [comment]
> @DoGab i added the extraContainers property to the setupJob config [5ae912a](https://github.com/zitadel/zitadel-charts/commit/5ae912aef02152d905856a00c48168312e61f09f). Please let me know if it helps with making it compatible with Istio.

Perfect, thank you! I'll test it and let you know :)

**Comment by thesephirot** [comment]
the installation of zitadel fails:

`helm install --namespace zitadel --create-namespace my-zitadel zitadel/zitadel \
  --set zitadel.masterkey="MasterkeyNeedsToHave32Characters" \
  --set zitadel.configmapConfig.ExternalSecure=false \
  --set zitadel.configmapConfig.TLS.Enabled=false \
  --set zitadel.secretConfig.Database.cockroach.User.Password="a-zitadel-db-user-password" \
  --set replicaCount=1
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: PodDisruptionBudget "crdb-budget" in namespace "zitadel" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "my-zitadel": current value is "crdb"`

**Comment by eliobischof** [comment]
> tadel/zi

If you want to test it, I guess you need to specify the chart by path ./charts/zitadel

**Comment by thesephirot** [comment]
> If you want to test the unreleased chart from this branch, I guess you need to specify the chart by path ./charts/zitadel
 my bad, choosing the right branch helps massively

**Comment by thesephirot** [comment]
`helm install --namespace zitadel --create-namespace my-zitadel zitadel/zitadel`

the --namespace --create-namespace seems duplicated to me

**Comment by eliobischof** [comment]
> `helm install --namespace zitadel --create-namespace my-zitadel zitadel/zitadel`
> 
> the --namespace --create-namespace seems duplicated to me

fixed it

**Comment by thesephirot** [comment]
after deleting the helm releases, the jobs and namespace are still in place.

`zitadel              crdb-init-jmd2q                                 0/1     Completed   0               20m
zitadel              my-zitadel-init-jd55k                           0/1     Completed   0               5m19s
zitadel              my-zitadel-setup-v8844                          0/1     Completed   0               5m7s`

don't we want to delete all created resources ? 

(the namespace might be a exception to this)

**Comment by eliobischof** [comment]
> after deleting the helm releases, the jobs and namespace are still in place.
> 
> `zitadel crdb-init-jmd2q 0/1 Completed 0 20m zitadel my-zitadel-init-jd55k 0/1 Completed 0 5m19s zitadel my-zitadel-setup-v8844 0/1 Completed 0 5m7s`
> 
> don't we want to delete all created resources ?
> 
> (the namespace might be a exception to this)

Garbage collection of helm hooks is not yet supported, unfortunately https://helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases

I mentioned this in the README.md https://github.com/zitadel/zitadel-charts/pull/48/commits/58b0e2226aea45c07a6bf78b706b187a3e8762c1.

Namespaces are handled differently by Helm.

**Comment by eliobischof** [comment]
@thesephirot the tests pass more reliably, now. I'm sure they failed because of eventual consistency. Increasing the check retries helped.
Can you review again, plz?

**Review by thesephirot — APPROVED** [review]
tested.

**Pull request merged**
