### PR TITLE
chore: fix comment

### PR DESCRIPTION
**Pull request by jessebot**
### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [ ] No debug or dead code
- [x] My code has no repetitions
- [x] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] If possible, [the test configuration](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/test/installation/config_test.go) is adjusted so acceptance tests cover my changes

The comment was little unclear before and this just fixes the grammar so it's a bit more readable. Happy to bump the chart version as well if you'd like.

Thanks for maintaining Zitadel :)

### CODE REVIEW

**Review by fforootd — APPROVED** [review]

**Comment by fforootd** [comment]
@jessebot thanks for this PR you are right.

@eliobischof either I am blind or do not get it, but why is the CI failing?
IMO this does not need a version bump.

**Comment by fforootd** [comment]
> > @jessebot thanks for this PR you are right.
> > @eliobischof either I am blind or do not get it, but why is the CI failing?
> > IMO this does not need a version bump.
> 
> Unfortunately, the chart-testing CLI is not smart enough to differentiate comments from other changes in the values.yaml. I'll see what I can do.

Uh my bad I thought we fixed that already 😁

**Comment by eliobischof** [comment]
> Would you like me to bump the chart version to make CI happy? :)

I used my superpowers 😜

**Comment by eliobischof** [comment]
@jessebot thank you for contibuting! If you'd like to have a small gift, send us a mail to hi@zitadel.com. We will send you a form for the details.

**Pull request merged**
