### PR TITLE
fix: remove illegal characters from port name

### PR DESCRIPTION
**Pull request by ameijboom**
While deploying Zitadel on our test cluster, we encountered an issue with the port name that was caused by the appProtocol we're using.

```
Invalid value: "kubernetes.io/h2c-server": a lowercase RFC 1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric charact
er (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
```

In this PR, we strip invalid characters from the protocol in the port name of the service.

### Definition of Ready

- [x] I am happy with the code
- [x] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [x] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [x] No debug or dead code
- [x] My code has no repetitions
- [x] Documentation/examples are up-to-date
- [x] All non-functional requirements are met
- [x] If possible, [the test configuration](https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/test/installation/config_test.go) is adjusted so acceptance tests cover my changes

### CODE REVIEW

**Review by eliobischof — CHANGES_REQUESTED** [review]
Thanks for the PR.

At least the port reference in the service monitor needs to be updated too, right?

image

**Comment by ameijboom** [comment]
You're correct. I've updated my PR accordingly.

**Comment by eliobischof** [comment]
> You're correct. I've updated my PR accordingly.

I don't see the change :smile:

**Comment by ameijboom** [comment]
Blunder on my part, should be all good now.

**Review by eliobischof — APPROVED** [review]
Hey @ameijboom, thanks for the fix.

If you'd like us to send you a small gift, please send us a mail to hi@zitadel.com. You will receive a form with questions like your shirt size and address.

**Pull request merged**
