### PR TITLE
feat: Add securityContext settings to machinekey container

### PR DESCRIPTION
**Pull request by lusu007**

### CODE REVIEW

**Comment by eliobischof** [comment]
Thanks a lot for the PR. I'll look into it asap.

**Comment by eliobischof** [comment]
I'll look into it in the current sprint.

**Comment by eliobischof** [comment]
Thanks again for your contribution @lusu007 :tada: Looks good to me.

If you would like us to show our appreciation by sending you some swag, send us a mail to hi@zitadel.com. We will then send you a form with some questions about the shirt size and other details. I think I forgot to mention this on your last contribution. Mea culpa, sorry!

**Review by eliobischof — APPROVED** [review]

**Comment by lusu007** [comment]
Hey @eliobischof,

Thank you for your kind words. I have just sent you an email. 😊
I'm always happy to help!

**Pull request merged**
